[[Glossary]]
== Glossary

[glossary]
Alias:: A name of a host in the inventory that is different from the actual
hostname of the host.

AMI:: Amazon Machine Image, a virtual machine image in the Amazon Elastic Compute Cloud, also known as _EC2_.

Ansible, Inc.:: The company that manages the Ansible project.

Ansible Galaxy:: A https://galaxy.ansible.com[repository] of Ansible roles contributed by the community.

Ansible Tower:: A proprietary web-based dashboard and REST interface for controlling
Ansible, sold by Ansible, Inc.

Check mode:: An optional mode when running a playbook. When check mode is enabled, and when Ansible executes a playbook, it will not make any changes to remote
hosts. Instead, it will simply report whether each task would have changed the
state of the host. Sometimes referred to as _dry run_ mode.

CIDR:: Classless interdomain routing, a notation for specifying a range of IP
addresses, used when defining Amazon EC2 security groups.

Configuration management:: A process for ensuring that servers are in the proper
state for doing their job. By _state_, we mean things like the configuration files for server applications
have the correct values, the proper files are present, the correct services are
running, the expected user accounts are present, permissions are set correctly, and so on.

Convergence:: A property of configuration management systems whereby the system
will execute multiple times against a server in order to get the server to reach
the desired state, with each execution bringing the server closer to the desired
state. Convergence is most closely associated with the CFEngine configuration
management system. Convergence doesn't really apply to Ansible, which puts
servers into desired states after a single execution.

Complex arguments:: Arguments passed to modules that are of type list or dictionary.

Container:: A form of server virtualization in which the virtualization is
implemented at the operating system level, so that the virtual machine instance
shares the same kernel as the host. Docker is the most well-known container
technology.

Control machine:: The computer that you run Ansible on that is used to control
the remote hosts.

Control socket:: A Unix domain socket that SSH clients use to connect to a
remote host when SSH multiplexing is enabled.

ControlPersist:: A synonym for SSH multiplexing.

Declarative:: A type of programming language in which the programmer describes the
desired output, not the procedure for how to compute the output. Ansible's
playbooks are declarative. SQL is another example of a declarative language.
Contrast with _procedural_ languages, such as Java and Python.

Deployment:: The process of bringing software up onto a live system.

DevOps:: IT buzzword that gained popularity in the mid-2010s.

Dry run:: See _Check mode_.

DSL:: Domain-specific language. In systems that use DSLs, the user interacts
with the systems by writing text files in the domain-specific language and then
runs those files through the system. DSLs are not as powerful as general-purpose
programming languages, but (if designed well) they are easier to read and write
than general-purpose programming languages. Ansible exposes a DSL that uses YAML
syntax.

Dynamic inventory:: Source that provides Ansible with information about
hosts and groups at playbook execution time.

EBS:: Elastic Block Store. On Amazon EC2, an EBS refers to a persistent disk
that can be attached to instances.

Fact:: A variable that contains information about a specific host.

Glob:: A pattern used by Unix shells to match against filenames. For
example, +*.txt+ is a glob that matches all files that end in +.txt+.

Group:: A named collection of hosts.

Handler:: Similar to a task, except that handlers execute only in response to a
task that is configured to notify the handler on change of state.

Host:: A remote server managed by Ansible.

IAM:: Identity and Access Management, a feature of Amazon's Elastic Compute
Cloud that allows you to manage user and group permissions.

Idempotent:: An action is idempotent if executing the action multiple times has
the same effect as executing it once.

Instance:: A virtual machine. The term is commonly used to refer to a virtual
machine running inside an infrastructure-as-a-service cloud, such as Amazon's
Elastic Cloud Compute (EC2).

Inventory:: The list of hosts and groups.

Lookups:: Code that executes on the control machine to obtain some
configuration data needed by Ansible while a playbook is running.

Module:: Ansible script that performs one specific task. Examples include creating a user account, installing a package, or starting a service. Most Ansible modules are idempotent.

Orchestration:: Performing a series of tasks in a well-specified order on a
collection of servers. Orchestration is often needed for performing deployments.

Pattern:: Ansible syntax for describing which hosts to run a play against.

Play:: Associates a set of hosts with a list of tasks to perform on that host.

Playbook:: An Ansible script. It specifies a list of plays and a collection of
hosts to execute the plays against.

Registered variable:: A variable created by using the +register+ clause in a
task.

Role:: An Ansible mechanism for bundling together a collection of tasks,
handlers, files, templates, and variables.
+
For example, an +nginx+ role might contain tasks for installing the Nginx
package, generating the Nginx configuration file, copying TLS certificate files,
and starting the Nginx service.

SSH multiplexing:: A feature of the OpenSSH SSH client that can reduce the time it
takes to make an SSH connection when making multiple SSH connections to the same
machine. Ansible uses SSH multiplexing by default to improve performance.

Task:: The unit of work in an Ansible play. A task specifies a module and its
arguments, as well as an optional name and some additional optional parameters.

TLS:: Transport Layer Security, a protocol used to secure communications between
web servers and browsers. TLS superseded an earlier protocol called _Secure Sockets Layer_ (SSL). Many people refer to TLS incorrectly as SSL.

Transport:: The protocol and implementation Ansible uses to connect to the
remote host. The default transport is SSH.

Vault:: A mechanism used by Ansible for encrypting sensitive data on disk.
Typically used to safely store secret data in a version-control system.

Vagrant:: A tool for managing virtual machines, intended for use by developers
to create reproducible development environments.

Virtualenv:: A mechanism for installing Python packages into an environment that
can be activated and deactivated. Enables a user to install Python packages
without root access and without polluting the global Python package library on
the machine.

VPC:: Virtual Private Cloud. A term used by Amazon EC2 to describe an isolated
network you can create for your EC2 pass:[<span class="keep-together">instances</span>].
